spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/RocketSaaS
spring.datasource.username=postgres
spring.datasource.password=jesuismasterspring2025
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernates.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
