spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/RocketSaas

spring.datasource.username=postgres
spring.datasource.password=jesuismasterspring2025
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernates.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
security.jwt.secret-key=f6367ba21be52cea650228d39a9a181d9ffb89f24516234fdf170652c35537c8
security.jwt.expiration-time=3600000


server.error.include-message=always
